import { readFile, writeFile, mkdir } from "node:fs/promises";
const root = new URL("../", import.meta.url),
  out = new URL("site/", root);
const m = JSON.parse(await readFile(new URL("manifesto.json", out), "utf8"));
const esc = (s) =>
  s.replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ],
  );
await mkdir(out, { recursive: true });
const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Style Science — An AI Design Manifesto</title><meta name="description" content="Design deserves better questions. A manifesto for explicit knowledge, distinctive work and accountable AI design.">
<meta name="theme-color" content="#ece9df"><link rel="icon" href="./mark.svg" type="image/svg+xml"><link rel="stylesheet" href="./style.css"><link rel="preload" href="./fonts/InterVariable.woff2" as="font" type="font/woff2" crossorigin>
<meta property="og:title" content="Style Science — Design Deserves Better Questions"><meta property="og:description" content="An AI design manifesto. Eight commitments to work we can understand, question and improve."><meta property="og:type" content="website"><link rel="canonical" href="https://jongos.github.io/style-science/"></head>
<body><a class="skip" href="#manifesto">Skip to the manifesto</a>
<header class="mast"><a class="wordmark" href="#top" aria-label="Style Science home"><span class="mark" aria-hidden="true">✳</span> Style Science</a><nav aria-label="Primary"><a href="#manifesto">Manifesto</a><a href="#canvas">The Canvas</a><a href="https://github.com/jongos/style-science">Source ↗</a></nav></header>
<main id="top"><section class="hero" aria-labelledby="hero-title"><div class="hero-meta"><span>Design / intelligence / responsibility</span><span>Statement 001 — October 2026</span></div>
<h1 id="hero-title">Design Deserves<br><span>Better Questions.</span></h1>
<div class="hero-bottom"><div class="study-mark" aria-hidden="true"><svg viewBox="0 0 240 180"><path d="M0 90h240M120 0v180"/><circle cx="120" cy="90" r="69"/><rect x="70" y="40" width="100" height="100"/><circle class="point" cx="170" cy="40" r="8"/><path d="M12 168L228 12"/></svg><span>Form is a relationship.</span></div><div class="opening"><p class="lead">${esc(m.introduction)}</p><p>${esc(m.position)}</p><a class="read-link" href="#manifesto">Read Our Commitments <span aria-hidden="true">↓</span></a></div></div></section>
<section class="manifesto section" id="manifesto" aria-labelledby="manifesto-title"><div class="section-label"><span>01 / The manifesto</span><h2 id="manifesto-title">Eight Commitments<br>to Better Work.</h2><p>For the people who build design systems.<br>And the systems that make designs.</p></div><div class="principles">${m.principles.map((p, i) => `<article class="principle"><span class="number" aria-hidden="true">${String(i + 1).padStart(2, "0")}</span><div><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p></div></article>`).join("")}</div></section>
<section class="experiment" aria-labelledby="experiment-title"><div class="experiment-copy"><span class="eyebrow">02 / A small study</span><h2 id="experiment-title">One Relationship.<br>Many Expressions.</h2><p>Move the interval. The elements stay the same; their relationship changes. Consider where you see one group, and where you see several.</p><p class="caption">A geometric demonstration, not a measure of beauty.</p><div class="control"><label for="interval">Interval <output id="interval-value" for="interval">24</output></label><input id="interval" type="range" min="12" max="56" value="24" step="1" aria-describedby="interval-note"><p id="interval-note">Use the arrow keys to make small adjustments.</p></div></div><div class="apparatus"><svg id="study" viewBox="0 0 560 360" role="img" aria-label="Two arrays of seven circles. Adjust the interval to change their spacing."><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="currentColor" stroke-width=".5"/></pattern></defs><rect width="560" height="360" fill="url(#grid)" class="grid"/><path d="M280 0v360M0 180h560" class="axis"/>${Array.from({ length: 14 }, (_, i) => `<circle data-point="${i}" cx="${280 + ((i % 7) - 3) * 24}" cy="${i < 7 ? 130 : 230}" r="${i < 7 ? 10 : 5}" class="${i < 7 ? "large-point" : "small-point"}"/>`).join("")}</svg><div class="apparatus-caption"><span>Position = anchor + n × interval</span><span>Same elements / different spacing</span></div></div></section>
<section class="canvas section" id="canvas" aria-labelledby="canvas-title"><div class="section-label"><span>03 / From conviction to code</span><h2 id="canvas-title">The Generative<br>Design Canvas.</h2></div><div class="canvas-body"><p class="lead">Knowledge you can carry.<br>Decisions you can inspect.</p><p>The GDC is the engineering foundation of Style Science: a portable package of explicit design knowledge and executable checks. JavaScript and Python consumers can use the same verification contract. Dazzler is its first consumer.</p><div class="facts"><div><span class="fact-value">57</span><span>preserved knowledge sources</span></div><div><span class="fact-value">113</span><span>source-reference relationships</span></div><div><span class="fact-value">0.1</span><span>initial core version</span></div></div><p class="boundary">Today, the core checks declared constraints such as contrast, overflow, text presence and style locks. It reports pass, fail or unknown. Its broader effect on design quality has not yet been established.</p><a class="source-link" href="https://github.com/jongos/style-science">Explore the Core <span aria-hidden="true">↗</span></a></div></section>
<section class="closing" aria-label="Our commitment"><p>${esc(m.closing)}</p><div class="pledge"><span class="mark" aria-hidden="true">✳</span><p>${esc(m.pledge)}</p></div></section></main>
<footer><div><strong>Style Science</strong><span>An open investigation into design.</span></div><div class="footer-links"><a href="./manifesto.md">Read as Text ↗</a><a href="https://github.com/jongos/style-science">GitHub ↗</a><a href="#top">Back to Top ↑</a></div><p class="credits">Original manifesto by Style Science. Design by <a href="https://jongos.github.io/Dazzler/">Dazzler</a>. Typographic voice: Inter by Rasmus Andersson. <a href="./fonts/LICENSE.txt">Font license</a>. Written in the tradition of principled industrial design; not a text by or an endorsement from Dieter Rams.</p></footer><script type="module" src="./app.js"></script></body></html>`;
await writeFile(new URL("index.html", out), html);
await writeFile(
  new URL("manifesto.md", out),
  `# ${m.title}\n\n${m.introduction}\n\n${m.position}\n\n${m.principles.map((p, i) => `## ${i + 1}. ${p.title}\n\n${p.body}`).join("\n\n")}\n\n${m.closing}\n\n${m.pledge}\n\n---\n\nAn original Style Science manifesto. October 2026.\n`,
);
console.log("Built Style Science landing page and text edition.");
